parameters:
    core.faye.endpoint:      'http://localhost:3000/’
    core.faye.adapter.class: 'Nc\FayeClient\Adapter\CurlAdapter'
    core.faye.client.class:  'Nc\FayeClient\Client'

services:
    core.faye.adapter:
        class:     %core.faye.adapter.class%

    core.faye.client:
        class:     %core.faye.client.class%
        arguments:
            - @acme_demo.faye.adapter
            - %acme_demo.faye.endpoint%

    render_module:
            class:     "App\Bundle\CoreBundle\Service\RenderModuleService"
            arguments: ['@service_container']
