parameters:
#    operadores_admin.example.class: Operadores\Bundle\AdminBundle\Example

services:
#    operadores_admin.example:
#        class: %operadores_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
