parameters:
#    operadores_core.example.class: Operadores\CoreBundle\Example

services:
    render_module:
        class:     "API\Bundle\CoreBundle\Service\RenderModuleService"
        arguments: ['@service_container']

    Guzzle
        class: %guzzle.client.class%